CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT);
CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT, "email" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "rooms" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "turn_position" INTEGER, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "players" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "turn_position" INTEGER, "score" INTEGER, "user_id" INTEGER CONSTRAINT "players_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "room_id" INTEGER CONSTRAINT "players_room_id_fkey" REFERENCES "rooms"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "players_room_id_index" ON "players" ("room_id");
CREATE TABLE IF NOT EXISTS "boards" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "width" INTEGER, "height" INTEGER, "room_id" INTEGER CONSTRAINT "boards_room_id_fkey" REFERENCES "rooms"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "board_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "board_id" INTEGER CONSTRAINT "board_items_board_id_fkey" REFERENCES "boards"("id") ON DELETE CASCADE, "player_id" INTEGER CONSTRAINT "board_items_player_id_fkey" REFERENCES "players"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "slots" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "position" INTEGER, "board_id" INTEGER CONSTRAINT "slots_board_id_fkey" REFERENCES "boards"("id") ON DELETE CASCADE, "item_id" INTEGER CONSTRAINT "slots_item_id_fkey" REFERENCES "items"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "slots_board_id_index" ON "slots" ("board_id");
CREATE TABLE IF NOT EXISTS "messages" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "body" TEXT, "room_id" INTEGER CONSTRAINT "messages_room_id_fkey" REFERENCES "rooms"("id") ON DELETE CASCADE, "player_id" INTEGER CONSTRAINT "messages_player_id_fkey" REFERENCES "players"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "messages_room_id_index" ON "messages" ("room_id");
CREATE TABLE IF NOT EXISTS "player_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "player_id" INTEGER CONSTRAINT "player_items_player_id_fkey" REFERENCES "players"("id") ON DELETE CASCADE, "item_id" INTEGER CONSTRAINT "player_items_item_id_fkey" REFERENCES "items"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "glyph" TEXT, "value" INTEGER, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
INSERT INTO schema_migrations VALUES(20240517161659,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517164058,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517165131,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517165143,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517165150,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517165156,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517165222,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517183908,'2024-05-17T19:32:35');
INSERT INTO schema_migrations VALUES(20240517185224,'2024-05-17T19:32:35');
